### ISSUE TITLE
Fortran interface

### ISSUE THREAD

**Issue by mlminion** [NERSC/timemory-tutorials#18]
Jonathan Madsen  2:59 PM
@Michael Minion I found some of the old fortran stuff and realized I was manually handling the null character for strings. If you file an issue on github as a reminder to me I’ll make a fortran library which handles the conversion to C strings

Also, it would be useful to see how to compile timemory with an existing Makefile structure for Fortran.  Is there just a library that can be linked?

**Comment by jrmadsen** [comment]
Closed by [NERSC/timemory #183](https://github.com/NERSC/timemory/pull/183)

**Comment by jrmadsen** [comment]
The library is `ftimemory` (i.e. `libftimemory.so` and/or `libftimemory.a`)
